version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: kalgg/aggregator-go
      GO111MODULE: "on"
    docker:
      - image: kalgg/aggregator-go-build:0.0.5
    working_directory: ~/agg
jobs:
  test:
    executor: docker-publisher
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: make
      - run: make test
  build_push_deploy:
    executor: docker-publisher
    steps:
      - add_ssh_keys:
        fingerprints:
          - "f4:04:5b:2a:c5:96:f8:60:7c:dc:96:c2:f7:35:d7:ab"
      - checkout:
          path: aggregator-go
      - setup_remote_docker:
          version: 18.09.3
      - run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - run:
          name: Build Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker buildx build --platform linux/amd64,linux/arm/v7,linux/arm64 -t $IMAGE_NAME:$TAG -t $IMAGE_NAME:latest --push -f aggregator-go/config/docker/main/Dockerfile .
      - run:
        name: Deploy to Host RPI 1
        command: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          ssh -o StrictHostKeyChecking=no ubuntu@$HOST_RPI_1 "kubectl set image deployment/agg agg=$IMAGE_NAME:$TAG"
  build_e2e_test:
    executor: docker-publisher
    steps:
      - checkout:
          path: aggregator-go
      - setup_remote_docker:
          version: 18.09.3
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:e2e -f aggregator-go/config/docker/benchmark/Dockerfile .
      - run:
          name: Archive Docker image
          command: docker save -o e2e.tar $IMAGE_NAME:e2e
      - persist_to_workspace:
          root: .
          paths:
            - ./e2e.tar
  e2e_test:
    executor: docker-publisher
    steps:
      - setup_remote_docker:
          version: 18.09.3
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Load Docker image
          command: |
            docker load -i /tmp/workspace/e2e.tar
      - run:
          name: Start redis
          command: |
            docker run --name redis -p 6379:6379 -d redis
      - run:
          name: Start test
          command: |
            docker run --network container:redis -e NODE_NAME=agg -e REDIS_URL=redis:6379 $IMAGE_NAME:e2e
workflows:
  version: 2.1
  build-master:
    jobs:
      - test
      - build_e2e_test:
          requires:
            - test
      - e2e_test:
          requires:
            - build_e2e_test
      - build_push_deploy:
          filters:
            branches:
              only:
                - master
