version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: kalgg/aggregator-go
    docker:
      - image: kalgg/aggregator-go-build:0.0.1
jobs:
  test:
    executor: docker-publisher
    working_directory: /go/src/github.com/kal-g/aggregator-go
    steps:
      - checkout
      - setup_remote_docker
      - run: go get -v -t -d ./...
      - run: make
      - run: make test
  build_image:
    executor: docker-publisher
    steps:
      - checkout:
          path: aggregator-go
      - setup_remote_docker:
          version: 18.09.3
      - run:
          name: Build Docker image
          command: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t $IMAGE_NAME:$TAG -t $IMAGE_NAME:latest -f aggregator-go/config/docker/main/Dockerfile .
      - run:
        name: Archive Docker image
        command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
        root: .
        paths:
          - ./image.tar
  push_image:
    executor: docker-publisher
    steps:
      - checkout:
          path: aggregator-go
      - setup_remote_docker:
          version: 18.09.3
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Push Docker image
          command: |
            docker load -i /tmp/workspace/image.tar
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push $IMAGE_NAME
workflows:
  version: 2.1
  build-master:
    jobs:
      - test
      - build_image:
          requires:
            - test
      - push_image:
          requires:
            - build_image
          filters:
            branches:
              only:
                - master
