version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: kalgg/aggregator-go
    docker:
      - image: kalgg/aggregator-go-build:0.0.2
jobs:
  test:
    executor: docker-publisher
    working_directory: /go/src/github.com/kal-g/aggregator-go
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: make
      - run: make test
      - run: make e2e_test
      - run: make benchmark
  build_image_and_push:
    executor: docker-publisher
    steps:
      - checkout:
          path: aggregator-go
      - setup_remote_docker:
          version: 18.09.3
      - run:
          name: Build Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker buildx build --platform linux/amd64,linux/arm/v7, -t $IMAGE_NAME:$TAG -t $IMAGE_NAME:latest -f aggregator-go/config/docker/main/Dockerfile .
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push $IMAGE_NAME
  deploy:
    executor: docker-publisher
    steps:
      - add_ssh_keys:
          fingerprints:
            - "f4:04:5b:2a:c5:96:f8:60:7c:dc:96:c2:f7:35:d7:ab"
      - run:
          name: Deploy to Host RPI 1
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@$HOST_RPI_1 "docker stop aggregator-go_1 && docker rm aggregator-go_1 && docker pull kalgg/aggregator-go:latest && docker run -p 50051:50051 --name aggregator-go_1 -d kalgg/aggregator-go:latest"

workflows:
  version: 2.1
  build-master:
    jobs:
      - test
      - build_image_and_push:
          requires:
            - test
          #filters:
            #branches:
              #only:
                #- master
      - deploy:
          requires:
            - build_image_and_push
