version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: kalgg/aggregator-go
    docker:
      - image: kalgg/aggregator-go-build:0.0.1
jobs:
  test:
    executor: docker-publisher
    working_directory: /go/src/github.com/kal-g/aggregator-go
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: make
      - run: make test
  build_image:
    executor: docker-publisher
    steps:
      - checkout:
          path: aggregator-go
      - setup_remote_docker:
          version: 18.09.3
      - run:
          name: Build Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t $IMAGE_NAME:$TAG -t $IMAGE_NAME:latest -f aggregator-go/config/docker/main/Dockerfile .
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME:latest
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  build_e2e_test:
    executor: docker-publisher
    steps:
      - checkout:
          path: aggregator-go
      - setup_remote_docker:
          version: 18.09.3
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:e2e -f aggregator-go/config/docker/benchmark/Dockerfile .
      - run:
          name: Archive Docker image
          command: docker save -o e2e.tar $IMAGE_NAME:e2e
      - persist_to_workspace:
          root: .
          paths:
            - ./e2e.tar
  e2e_test:
    executor: docker-publisher
    steps:
      - setup_remote_docker:
          version: 18.09.3
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Load Docker image
          command: |
            docker load -i /tmp/workspace/e2e.tar
      - run:
          name: Start redis
          command: |
            docker run --name redis -p 6379:6379 -d redis
      - run:
          name: Start test
          command: |
            docker run --network container:redis $IMAGE_NAME:e2e
          
  push_image:
    executor: docker-publisher
    steps:
      - checkout:
          path: aggregator-go
      - setup_remote_docker:
          version: 18.09.3
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Push Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker load -i /tmp/workspace/image.tar
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$TAG
workflows:
  version: 2.1
  build-master:
    jobs:
      - test
      - build_image:
          requires:
            - test
      - build_e2e_test:
          requires:
            - test
      - e2e_test:
          requires:
            - build_e2e_test
      - push_image:
          requires:
            - build_image
          filters:
            branches:
              only:
                - master
