version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: kalgg/aggregator-go
    docker:
      - image: kalgg/aggregator-go-build:0.0.5
jobs:
  test:
    executor: docker-publisher
    working_directory: /go/src/github.com/kal-g/aggregator-go
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: make
      - run: make test
  build_and_push_image:
    executor: docker-publisher
    environment:
    steps:
      - checkout:
          path: aggregator-go
      - setup_remote_docker:
          version: 18.09.3
      - run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - run:
          name: Build Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker buildx build --platform linux/amd64,linux/arm/v7 -t $IMAGE_NAME:$TAG -t $IMAGE_NAME:latest --push -f aggregator-go/config/docker/main/Dockerfile .
  build_e2e_test:
    executor: docker-publisher
    steps:
      - checkout:
          path: aggregator-go
      - setup_remote_docker:
          version: 18.09.3
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:e2e -f aggregator-go/config/docker/benchmark/Dockerfile .
      - run:
          name: Archive Docker image
          command: docker save -o e2e.tar $IMAGE_NAME:e2e
      - persist_to_workspace:
          root: .
          paths:
            - ./e2e.tar
  e2e_test:
    executor: docker-publisher
    steps:
      - setup_remote_docker:
          version: 18.09.3
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Load Docker image
          command: |
            docker load -i /tmp/workspace/e2e.tar
      - run:
          name: Start redis
          command: |
            docker run --name redis -p 6379:6379 -d redis
      - run:
          name: Start test
          command: |
            docker run --network container:redis $IMAGE_NAME:e2e
  deploy:
    executor: docker-publisher
    steps:
      - add_ssh_keys:
          fingerprints:
            - "f4:04:5b:2a:c5:96:f8:60:7c:dc:96:c2:f7:35:d7:ab"
      - run:
          name: Deploy to Host RPI 1
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@$HOST_RPI_1 "docker stop aggregator-go_1 && docker rm aggregator-go_1 && docker pull kalgg/aggregator-go:latest && docker run -p 50051:50051 --name aggregator-go_1 -d kalgg/aggregator-go:latest"
          
workflows:
  version: 2.1
  build-master:
    jobs:
      - test
      - build_e2e_test:
          requires:
            - test
      - e2e_test:
          requires:
            - build_e2e_test
      - build_and_push_image:
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build_and_push_image
          filters:
            branches:
              only:
                - master
