version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: kalgg/aggregator-go
    docker:
      - image: kalgg/aggregator-go-build:0.0.1
jobs:
  test:
    executor: docker-publisher
    working_directory: /go/src/github.com/kal-g/aggregator-go
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: make test
      - run: make e2e_test
      - run: make benchmark
  build_image:
    executor: docker-publisher
    steps:
      - checkout:
          path: aggregator-go
      - setup_remote_docker
      - run: ls
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:latest config/docker/main
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
workflows:
  version: 2.1
  build-master:
    jobs:
      - test
      - build_image:
          requires:
            - test
